config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
  devise_for :users
  
  scope 'users', module: 'users' do
    resources :users, only: [:show, :edit, :update]
    resources :recipes, only: [:show]
    resources :breakfast, only: [:show, :edit, :update]
    resources :meals, except: [:new, :index, :edit]
    resources :days, except: [:new, :index, :edit]
    resources :weeks, only: [:show, :create, :update]
    resources :shopping_emails, only: [:show]
    resources :charges, only: [:new, :create, :index]
  end

  scope 'admin', module: 'admin', as: 'admin' do
    resources :dashboard, only: [:index]
    resources :recipes
  end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :join_recipe_foods
  has_many :foods, through: :join_recipe_foods
  
  accepts_nested_attributes_for :join_recipe_foods, allow_destroy: true, reject_if: ['food_id'].blank?


  has_many :hotdrink_breakfast, foreign_key: 'hotdrink_id', class_name: 'Breakfast'
  has_many :fruit_breakfast, foreign_key: 'fruit_id', class_name: 'Breakfast'
  has_many :cereal_breakfast, foreign_key: 'cereal_id', class_name: 'Breakfast'
  has_many :protein_breakfast, foreign_key: 'protein_id', class_name: 'Breakfast'
  has_many :complement_breakfast, foreign_key: 'complement_id', class_name: 'Breakfast'

  has_many :starter_meal, foreign_key: 'starter_id', class_name: 'Meal'
  has_many :dish_meal, foreign_key: 'dish_id', class_name: 'Meal'
  has_many :dessert_meal, foreign_key: 'dessert_id', class_name: 'Meal'
  has_many :drink_meal, foreign_key: 'drink_id', class_name: 'Meal'
  has_many :complement_meal, foreign_key: 'complement_id', class_name: 'Meal'
  
  validates :title,
	presence: true,
	length: { in: 3..50 }
  validates :forhowmany,
	presence: true,
	numericality: { greater_than: 0 }
  validates :cookingtime,
	presence: true,
	numericality: { greater_than: 0 }
  validates :budget,
	presence: true
  validates :category,
	presence:true

  def total_kcal
    self.join_recipe_foods.map { |food| food.kcal}.sum
  end

  def total_prot
    self.join_recipe_foods.map { |food| food.protein}.sum
  end
  
  def total_lip
    self.join_recipe_foods.map { |food| food.lipid}.sum
  end

  def total_salt
    self.join_recipe_foods.map { |food| food.salt}.sum
  end

  def total_sugar
    self.join_recipe_foods.map { |food| food.sugar}.sum
  end

  def total_chol
    self.join_recipe_foods.map { |food| food.chol}.sum
  end

  def total_carb
    self.join_recipe_foods.map { |food| food.carb}.sum
  end

  def for_one
    self.total_kcal / self.forhowmany
  end

  def self.recipes_to_csv
	attributes = %w{id title forhowmany cookingtime budget category url vegan vegetarian porkless}

	CSV.generate(headers: true) do |csv|
	  csv << attributes

	  all.find_each do |recipe|
		csv << attributes.map{ |attr| recipe.send(attr) }
	  end
	end
  end

end

app/controllers/admin/recipes_controller.rb
class Admin::RecipesController < Admin::ApplicationController
  before_action :set_admin_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @admin_recipes = Recipe.all
	  @join_recipes = JoinRecipeFood.all
    @breakfast_categories = ["Hot Drink", "Juice", "Cereal (Breakfast)", "Protein (Breakfast)", "Option (Breakfast)"]
    @meal_categories = ["Starter", "Dish", "Fruit", "Drink", "Complement"]

    respond_to do |format|
      format.html
      if params[:notice] == "recipe"
        format.csv { send_data @admin_recipes.recipes_to_csv, filename: "recipes_nutriti.csv" }
      else params[:notice] == "join"
        format.csv { send_data @join_recipes.join_to_csv, filename: "join_recipe_foods_nutriti.csv" }
      end
    end
  end

  def show
  end

  def new
    @admin_recipe = Recipe.new
    @admin_recipe.join_recipe_foods.build
  end

  def edit
  end

  def create
    @admin_recipe = Recipe.new(admin_recipe_params)

    respond_to do |format|
      if @admin_recipe.save
        format.html { redirect_to admin_recipes_path, notice: 'Recipe was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update

    respond_to do |format|
      if @admin_recipe.update(admin_recipe_params)
        format.html { redirect_to admin_recipes_path, notice: 'Recipe was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @admin_recipe.join_recipe_foods.destroy_all
    @admin_recipe.destroy
    respond_to do |format|
      format.html { redirect_to admin_recipes_url, notice: 'Recipe was successfully destroyed.' }
    end
  end

  private
    def set_admin_recipe
      @admin_recipe = Recipe.find(params[:id])
    end

    def admin_recipe_params
      params
      .require(:recipe)
      .permit(:title, :forhowmany, :cookingtime, :category, :budget, :url, :vegan, :vegetarian, :porkless, join_recipe_foods_attributes: [:id, :food_id, :quantity, :_destroy])
    end

end

app/controllers/users/recipes_controller.rb
class Users::RecipesController < Users::ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
    @user_ratio = params[:ratio].to_f

    respond_to do |format|
      format.js {}
    end

  end
end

app/views/admin/recipes/_form.html.erb
<%= form_with(model: [:admin, @admin_recipe], local: true) do |f| %>
  <% if admin_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_recipe.errors.count, "error") %> prohibited this admin_recipe from being saved:</h2>

      <ul>
      <% admin_recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title%>
  <%= f.text_field :title, class:"form-control"%>
  <br>
  <%= f.label :forhowmany%>
  <%= f.number_field :forhowmany, min: 1, class:"form-control"%>
  <br>
  <%= f.label :cookingtime%>
  <%= f.number_field :cookingtime, step: 5, class:"form-control"%>
  <div class="d-flex flex-row mt-2">
    <div class="mr-5">
    <%= f.label :category, "Type de recette"%>
    <%= f.select :category, [["Starter"],["Dish"], ["Fruit"], ["Drink"], ["Complement"], ["Hot Drink"], ["Juice"], ["Cereal (Breakfast)"], ["Protein (Breakfast)"], ["Option (Breakfast)"]], class:"form-control"%>
    </div>
    <div class="mx-5">
    <%= f.label :budget, "Budget"%>
    <%= f.select :budget, [['Bon marché'],['Coût moyen'],['Assez Cher']], class:"form-control"%>
    </div>
  </div>
  <div class="d-flex flex-row mt-2">
    <%= f.label :vegan, "Vegan" %>
    <%= f.check_box :vegan %>
    <%= f.label :vegetarian, "Végétarien" %>
    <%= f.check_box :vegetarian %>
    <%= f.label :porkless, "Sans porc" %>
    <%= f.check_box :porkless %>
  </div>
  <%= f.label :url%>
  <%= f.text_field :url, class:"form-control"%>
  <br>

<p>Liste des ingrédients :</p>
  <div class="food">
    <%= f.fields_for :join_recipe_foods do |recipe_form| %>
        <%= render 'join_recipe_food_fields', f: recipe_form%>
    <% end %>
  </div>
  <br>
  <div>
  <%= link_to_add_association 'Ajouter un aliment', f, :join_recipe_foods, class:"btn btn-success", data: { association_insertion_node: '.food', association_insertion_method: :append } %>
  </div>
  <br>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/admin/recipes/_join_recipe_food_fields.html.erb
  <div class="nested-fields row my-1">
    <div>
      <%= link_to_remove_association "<i class='fas fa-trash-alt'></i>".html_safe, f, class:"text-danger"%>
      <%= f.label :name, "<h5>Aliment : </h5>".html_safe, class:"mb-1" %>
      <%= f.collection_select(:food_id, Food.all, :alim_code, :alim_name, {prompt: false}, {"data-live-search" => "true"})  %>
    </div>
    <div class="d-flex flex-row mt-1">
      <%= f.label :quantity, "Quantité en gramme", class:"mx-2" %>
      <%= f.number_field :quantity, step: :any, class:"form-control" %>
    </div>
    <script>
      $(function () {
          $('select').selectpicker();
      })
    </script>
  </div>

app/views/admin/recipes/edit.html.erb
<h1>Editer la recette</h1>

<div class="container">

<%= render 'form', admin_recipe: @admin_recipe %>

<%= link_to 'Voir la recette', admin_recipes_path, class:"btn btn-success" %> |
<%= link_to 'Retour', admin_recipes_path, class:"btn btn-primary" %>

</div>

app/views/admin/recipes/index.html.erb
<div class="text-center">
  <h1>Liste des Recettes</h1>
  <%= link_to 'Nouvelle Recette', new_admin_recipe_path, class:"btn btn-primary btn-lg" %>
  <%= link_to 'CSV Recipes', admin_recipes_path(notice: "recipe", format: :csv), class:"btn btn-success btn-lg" %>
  <%= link_to 'CSV Joins', admin_recipes_path(notice: "join", format: :csv), class:"btn btn-success btn-lg" %>
</div>

  <h2>Breakfast</h2>

<% @breakfast_categories.each do |item| %>
  <h4><%= item %></h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nom de la recette</th>
      <th>Pour combien de personnes</th>
      <th>Temps de préparation</th>
      <th>Budget</th>
      <th>Kcal</th>
      <th>Lien vers la recette</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_recipes.each do |admin_recipe| %>
      <% if admin_recipe.category ==  item %>
        <tr>
          <td><%= admin_recipe.title %></td>
          <td><%= admin_recipe.forhowmany %></td>
          <td><%= admin_recipe.cookingtime %></td>
          <td><%= admin_recipe.budget %></td>
          <td><%= admin_recipe.total_kcal %></td>
          <td><%= admin_recipe.url %></td>
          <td><%= link_to 'Show', admin_recipe_path(admin_recipe.id) %></td>
          <td><%= link_to 'Edit', edit_admin_recipe_path(admin_recipe.id) %></td>
          <td><%= link_to 'Destroy', admin_recipe_path(admin_recipe.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<% end %>


<br>

  <h2>Meal</h2>

<% @meal_categories.each do |item| %>
  <h4><%= item %></h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nom de la recette</th>
      <th>Pour combien de personnes</th>
      <th>Temps de préparation</th>
      <th>Budget</th>
      <th>Kcal</th>
      <th>Lien vers la recette</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_recipes.each do |admin_recipe| %>
      <% if admin_recipe.category ==  item %>
        <tr>
          <td><%= admin_recipe.title %></td>
          <td><%= admin_recipe.forhowmany %></td>
          <td><%= admin_recipe.cookingtime %></td>
          <td><%= admin_recipe.budget %></td>
          <td><%= admin_recipe.total_kcal %></td>
          <td><%= admin_recipe.url %></td>
          <td><%= link_to 'Show', admin_recipe_path(admin_recipe.id) %></td>
          <td><%= link_to 'Edit', edit_admin_recipe_path(admin_recipe.id) %></td>
          <td><%= link_to 'Destroy', admin_recipe_path(admin_recipe.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<% end %>

<br>

app/views/admin/recipes/new.html.erb
<h1>Nouvelle recette</h1>


<div class="container">

  <%= render 'form', admin_recipe: @admin_recipe %>

  <hr>
  <%= link_to 'Retour', admin_recipes_path, class:"btn btn-primary" %>
</div>

app/views/admin/recipes/show.html.erb
<h1 class=text-center><%= @admin_recipe.title %></h1>
<div class="text-center">
  Pour <%= @admin_recipe.forhowmany %> personne(s) |
  <%= @admin_recipe.cookingtime %> minute(s) |
  Budget : <%= @admin_recipe.budget %>
  <br>
  <div class="mt-2">
    <%= link_to "Voir la recette", @admin_recipe.url, target: :_blank, class:"btn btn-danger" %>
  </div>
</div>
<br>
<h2>Valeure nutritionnelle</h2>
<div><%= @admin_recipe.total_kcal %> kcal pour <%= @admin_recipe.forhowmany %></div>
<div>Soit : <%= @admin_recipe.total_kcal / @admin_recipe.forhowmany %> kcal par personne</div>
<div>dont : <%= @admin_recipe.total_prot / @admin_recipe.forhowmany %> gramme de proteine(s) par personne</div>

<br>
<h2>Liste des ingrédients</h2>
  <ul>
    <% @admin_recipe.join_recipe_foods.each do |food| %>
      <li>
        <%= food.food.alim_name %> =
        <%= food.quantity %> gramme(s)
      </li>
    <% end %>
  </ul>

<h2>Régime alimentaire</h2>
  <% if@admin_recipe.vegan == true %>
    <div>Vegan</div>
  <% end %>
  <% if@admin_recipe.vegetarian == true %>
    <div>Végétarien</div>
  <% end %>
  <% if@admin_recipe.porkless == true %>
    <div>Sans porc</div>
  <% end %>
<hr>
<div class="text-center">
<%= link_to 'Edit', edit_admin_recipe_path(@admin_recipe), class:"btn btn-success" %> |
<%= link_to 'Back', admin_recipes_path, class:"btn btn-primary" %>
</div>