config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
  devise_for :users
  
  scope 'users', module: 'users' do
    resources :users, only: [:show, :edit, :update]
    resources :recipes, only: [:show]
    resources :breakfast, only: [:show, :edit, :update]
    resources :meals, except: [:new, :index, :edit]
    resources :days, except: [:new, :index, :edit]
    resources :weeks, only: [:show, :create, :update]
    resources :shopping_emails, only: [:show]
    resources :charges, only: [:new, :create, :index]
  end

  scope 'admin', module: 'admin', as: 'admin' do
    resources :dashboard, only: [:index]
    resources :recipes
  end

end

app/models/user.rb
class User < ApplicationRecord
  after_create :user_week
  after_create :welcome_mail
  after_update :get_age

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :recoverable, :rememberable, :validatable

  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

  has_one :week
  has_one :breakfast

  def get_age
    if self.birthdate
      (Time.now.year - self.birthdate.year)
    else
      return 0
    end
  end

  def mb
    if self.gender == "Homme"
      ((13.707 * self.weight) + (492.3 * (self.height / 100.00).to_d) - (6.673 * self.get_age) + 77.607).to_d
    elsif self.gender == "Femme"
      ((9.740 * self.weight) + (172.9 * (self.height / 100.00).to_d) - (4.737 * self.get_age) + 667.051).to_d
    else
      return 0.0
    end
  end

  def drc
    if (self.gender == "Homme")
      self.mb * self.physical_activity.to_d * self.objective.to_f
    else
      self.mb * self.physical_activity.to_d * self.objective.to_f
    end
  end

  def welcome_mail
    UserMailer.welcome_email(self).deliver_now
  end

  def incomplete_profile?
    self.drc == 0.0
  end

  def needbymeal(meal)
    if meal == self.breakfast
      self.breakfast_needs
    elsif meal == "Lunch"
      self.lunch_needs
    else meal == "Dinner"
      self.dinner_needs
    end
  end

  def breakfast_needs
    (self.drc / 100) * 25
  end

  def lunch_needs
    (self.drc / 100) * 40
  end

  def dinner_needs
    (self.drc / 100) * 35
  end

  def shopping_cart
    array = []
    sorted = []
    self.week.days.each  do |day|
      day.meals.each do |meal|
        meal.recipes.each do |recipe|
          if meal == self.breakfast
            recipe.join_recipe_foods.each do |join|
              array << {join.food.alim_name.match('^[^\,(]*').to_s => (join.quantity.to_f * (1.0/join.recipe.forhowmany.to_f).to_f) * (self.needbymeal(meal)/meal.kcal).to_f}
            end
          else   
            recipe.join_recipe_foods.each do |join|
              array << {join.food.alim_name.match('^[^\,(]*').to_s => (join.quantity.to_f * (1.0/join.recipe.forhowmany.to_f).to_f) * (self.needbymeal(meal.category)/meal.kcal).to_f}
            end
          end
        end
      end
    end

    array.reduce {|acc, h| acc.merge(h) {|_,v1,v2| v1 + v2 }}
  end


  def pa_title
    if self.physical_activity == "1.2"
      "Sedentaire"
    elsif self.physical_activity == "1.375"
      "Activité physique légère"
    elsif self.physical_activity == "1.55"
      "Activité physique modérée"
    elsif self.physical_activity == "1.725"
      "Activité physique intense"
    elsif self.physical_activity == "1.9"
      "Activité physique très intense"
    else
      "Non renseigné"
    end
  end

  def obj_title
    if self.objective == "1"
      'Garder la ligne'
    elsif self.objective == "0.9"
      'Maigrir'
    else self.objective == "1.1"
      'Grossir'
    end
  end

  
  private
  
  def user_week
    user_breakfast = Breakfast.create(user_id: self.id)
    user_breakfast.generate
    user_breakfast.total_kcal
    user_week = Week.create(user_id: self.id)
    user_week.generate
  end
end

app/models/week.rb
class Week < ApplicationRecord
  belongs_to :user

  belongs_to :monday, class_name: 'Day', optional: true
  belongs_to :tuesday, class_name: 'Day', optional: true
  belongs_to :wednesday, class_name: 'Day', optional: true
  belongs_to :thursday, class_name: 'Day', optional: true
  belongs_to :friday, class_name: 'Day', optional: true
  belongs_to :saturday, class_name: 'Day', optional: true
  belongs_to :sunday, class_name: 'Day', optional: true

  def generate
    @monday = Day.new.generate("Monday", self.user)
    @monday.save
    @tuesday = Day.new.generate("Tuesday", self.user)
    @tuesday.save
    @wednesday = Day.new.generate("Wednesday", self.user)
    @wednesday.save
    @thursday = Day.new.generate("Thursday", self.user)
    @thursday.save
    @friday = Day.new.generate("Friday", self.user)
    @friday.save
    @saturday = Day.new.generate("Saturday", self.user)
    @saturday.save
    @sunday = Day.new.generate("Sunday", self.user)
    @sunday.save

    self.update(monday: @monday)
    self.update(tuesday: @tuesday)
    self.update(wednesday: @wednesday)
    self.update(thursday: @thursday)
    self.update(friday: @friday)
    self.update(saturday: @saturday)
    self.update(sunday: @sunday)

    return self
  end

  def days
    [self.monday,
    self.tuesday,
    self.wednesday,
    self.thursday,
    self.friday,
    self.saturday,
    self.sunday]
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  end

  def update  
    current_user.update(user_params)

    redirect_to user_path(current_user.id), flash:{notice: "Votre profil a été mis à jours"}
  end

private

  def user_params
    params
    .require(:user)
    .permit(:first_name, :last_name, :gender, :height, :weight, :birthdate, :physical_activity, :id)
  end
end

app/controllers/users/application_controller.rb
class Users::ApplicationController < ApplicationController
  before_action :authenticate_user!
  
  layout 'users'

  def user_incompleted
    if current_user.incomplete_profile?
      redirect_to edit_user_path(current_user.id)
    end
  end

  def only_premium
    if !user_signed_in? || !current_user.is_premium
      redirect_to root_path, flash: {error: "Cette action est réservée aux membres Premium !"}
    end
  end
end

app/controllers/users/breakfast_controller.rb
class Users::BreakfastController < Users::ApplicationController
  before_action :set_users_breakfast, only: [:show, :edit, :update]

  def show
    @meal = Breakfast.find(params[:id])
    @alim_groups = Food.all.map(&:alim_group).uniq
  
  end

  def edit
    @hotdrinks = Recipe.all.where(category: "Hot Drink")
    @fruits = Recipe.all.where(category: "Juice").or(Recipe.all.where(category: "Fruit"))
    @cereals = Recipe.all.where(category: "Cereal (Breakfast)")
    @proteins = Recipe.all.where(category: "Protein (Breakfast)")
    @options = Recipe.all.where(category: "Option (Breakfast)")
  end

  def update
    respond_to do |format|
      if @users_breakfast.update(users_breakfast_params)
        @users_breakfast.total_kcal
        current_user.week.generate
        format.html { redirect_to root_path, notice: "Petit déjeuner mis à jours avec success" }
      else 
        format.html { redirect_to :edit, error: "Petit dej non mis à jours" }
      end
    end
  end



  private
    def set_users_breakfast
      @users_breakfast = current_user.breakfast
    end

    def users_breakfast_params
      params
      .require(:breakfast)
      .permit(:hotdrink_id, :fruit_id, :cereal_id, :protein_id, :option_id, :id)
    end
end

app/controllers/users/charges_controller.rb
class Users::ChargesController < Users::ApplicationController
  before_action :incompleted
  before_action :already_premium

  def new
    if params[:notice] == "premium"
      @amount = 5 
      @formula = "Premium"
    else
      
    end
  end

  def index
    
  end
  
  def create
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })

    current_user.update(is_premium: true)
    
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  private

  def incompleted
    redirect_to root_path, flash:{error: "Veuillez compléter votre profil avant de poursuivre"} if current_user.incomplete_profile?
  end

  def already_premium
    redirect_to root_path, flash:{notice: "Vous êtes déjà premium"} if current_user.is_premium
  end
end

app/controllers/users/days_controller.rb
class Users::DaysController < Users::ApplicationController
  before_action :set_users_day, only: [:show, :update, :destroy]
  before_action :only_premium, only: [:show, :update, :destroy]

  def index
    @users_days = Day.all
  end

  def show
    @day = Day.find(params[:id])
    @alim_groups = Food.all.map(&:alim_group).uniq

  end

  def create
    @days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    @users_day = Day.new
    @users_day.generate(@days.sample, current_user)

    respond_to do |format|
      if @users_day.save
        format.html { redirect_to @users_day, notice: 'Day was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @users_day.update(users_day_params)
        format.html { redirect_to @users_day, notice: 'Day was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @users_day.destroy
    respond_to do |format|
      format.html { redirect_to days_path, notice: 'Day was successfully destroyed.' }
    end
  end

  private
    def set_users_day
      @users_day = Day.find(params[:id])
    end

    def users_day_params
      params.fetch(:users_day, {})
    end
end

app/controllers/users/meals_controller.rb
class Users::MealsController < Users::ApplicationController
  before_action :set_meal, only: [:show, :update, :destroy]
  before_action :only_premium, only: [:show, :update, :destroy]

  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
    @alim_groups = Food.all.map(&:alim_group).uniq
  end

  def create
    category = ['Lunch','Dinner']
    @meal = Meal.new.generate(category.sample, current_user)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Votre repas a bien été créé.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to @meal, notice: 'Votre repas a bienété mis à jours.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Votre repas a bien été supprimé.' }
    end
  end

  private
    def set_meal
      @meal = Meal.find(params[:id])
    end

    def meal_params
      params.fetch(:meal, {})
    end
end

app/controllers/users/recipes_controller.rb
class Users::RecipesController < Users::ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
    @user_ratio = params[:ratio].to_f

    respond_to do |format|
      format.js {}
    end

  end
end

app/controllers/users/shopping_emails_controller.rb
class Users::ShoppingEmailsController < Users::ApplicationController
	before_action :only_premium, only: [:show, :update, :destroy]

  def show
	@user = current_user
	UserMailer.shopping_cart_email(@user).deliver_now
	redirect_to :week
  end

end

app/controllers/users/users_controller.rb
class Users::UsersController < Users::ApplicationController
  def show
  end

  def update
    current_user.update(user_params)
    current_user.week.generate
    
    if params[:commit] == "Mettre à jour mon profil"
      redirect_to user_path(current_user.id)
    else
      redirect_to root_path
    end

  end

  def edit 
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end
  

private

  def user_params
    params
    .require(:user)
    .permit(:first_name, :last_name, :gender, :height, :weight, :birthdate, :physical_activity, :objective, :id, :express, :vegan, :vegetarian, :porkless, :is_premium)
  end
end

app/controllers/users/weeks_controller.rb
class Users::WeeksController < Users::ApplicationController
  before_action :set_users_week, only: [:show, :edit, :update, :destroy]
  before_action :user_incompleted

  def show
    @alim_groups = Food.all.map(&:alim_group).uniq
  end

  def create
    @users_week = Week.new(users_week_params)

    respond_to do |format|
      if @users_week.save
        format.html { redirect_to @users_week, notice: 'Week was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @users_week.generate
        format.html { redirect_to @users_week, notice: 'Week was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  private
    def set_users_week
      @users_week = Week.find_by(user_id: current_user.id)
    end

    def users_week_params
      params.fetch(:users_week, {})
    end
end

app/views/users/weeks/show.html.erb
<div class="sidebar-wrapper"  hidden="true" id="nav">
  <nav class="sidenav flex-column scrollable">
    <table class="table table-borderless" >
      <h3 class="text-center">Liste de course</h3>
      <hr style="margin: 25px;" class="bold">
      <tbody>
		<div class="d-flex flex-row justify-content-center align-items-center">
      <% unless current_user.is_premium %>
        <span class="badge badge-pill badge-light"><i class="far fa-star mr-2"></i> Premium</span>
      <% end %>
		  <%= link_to "Recevoir la liste de course par email", shopping_email_path, data: { confirm: "Voulez vous recevoir votre liste par email ?" }, class:'btn btn-warning'%>
		</div>
		<br/>
        <% @alim_groups.each do |alim_group| %>
          <b class="ml-4"><%= alim_group.capitalize %></b>
          <table class="ml-4">
            <tbody>
            <% current_user.shopping_cart.each do |elem|%>
            <% food = Food.find_by("alim_name like?", "%#{elem[0]}%") %>
              <% if alim_group ==  food.alim_group %>            
                <tr>
                  <% if food.weight_for_one != 1%>
                    <td><%= (elem[1].ceil / food.weight_for_one).ceil%> <%= food.basic_unity%></td>
                  <% elsif elem[1].ceil < 999 %>
                    <td><%= elem[1].ceil%> <%= food.basic_unity%></td>
                  <% else %>
                    <td><%= (elem[1].ceil.to_f / 1000).ceil(2)%> <%= food.thousand_unity%></td>
                  <%end%>
                  <td class="bold"><%= elem[0]%></td>
                </tr>
              <% end %>
            <% end %>
            </tbody>
          </table>
                    <hr>
        <% end %>
      </tbody>
    </table>
    <br><br><br><br>
  </nav>
  <div class="blur" id="close">
  </div>
</div>

<div class="container-fluid">
  <div class="text-center d-flex flex-row justify-content-center">
    <div class="text-center flex-row mx-2">
      <%= form_with(model: current_user, method: 'put', local: true) do |f| %>
        <% if @users_week.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@users_week.errors.count, "error") %> prohibited this @users_week from being saved:</h2>
            <ul>
            <% @users_week.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        
          <%= f.label :express, "Express (-15min)" %>
          <%= f.check_box :express %> |
          <%= f.label :vegan %>
          <%= f.check_box :vegan %> |
          <%= f.label :vegetarian, "Végétarien" %>
          <%= f.check_box :vegetarian %> |
          <%= f.label :porkless, "Sans porc" %>
          <%= f.check_box :porkless %>


          <%= f.submit "Générer une nouvelle semaine", class:"btn btn-success ml-2" %>

      <% end %>
    </div>

    <div class="text-center flex-row mx-2">
      <button name="button" id="shopping-list"class="btn btn-danger">Afficher Liste de Course</button> 
    </div>
  </div>

  <div class="d-flex flex-row mt-3">
    <% current_user.week.days.each do |day|%>
      <div class="card mx-1 border-bottom border-left border-right border-success" style="width: 16rem;">
        <div class="card-header d-flex justify-content-between bg-success">
          <%= link_to day.name, day_path(day.id), class:"text-white"%> 
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item text-light text-center bg-light">
            <b><%= link_to "Petit Déjeuner", breakfast_path(current_user.breakfast.id), class:"text-warning"%></b>
          </li>
          <ul class="list-group-item size-li-planning border-bottom border-success">  
            <li class=""><%= current_user.breakfast.hotdrink.title%></li>
            <li class=""><%= current_user.breakfast.fruit.title%></li>
            <li class=""><%= current_user.breakfast.cereal.title%></li>
            <li class=""><%= current_user.breakfast.protein.title%></li>
            <li class=""><%= current_user.breakfast.option.title%></li>
            
          </ul>
          <li class="list-group-item text-light text-center bg-light">
            <b><%= link_to "Déjeuner", meal_path(day.lunch.id), class:"text-warning"%></b>
          </li>
          <ul class="list-group-item size-li-planning border-bottom border-success">    
            <li class=""><i class="fas fa-plus-circle text-success"></i> <%= link_to day.lunch.starter.title, recipe_path(day.lunch.starter.id, ratio: current_user.needbymeal(day.lunch.category)/day.lunch.kcal),  remote: true, "data-target" => "#recipeModal", "data-toggle" =>"modal", class:"text-dark text-decoration-none" %></li>
            <li class=""><i class="fas fa-plus-circle text-success"></i> <%= link_to day.lunch.dish.title, recipe_path(day.lunch.dish.id, ratio: current_user.needbymeal(day.lunch.category)/day.lunch.kcal),  remote: true, "data-target" => "#recipeModal", "data-toggle" =>"modal", class:"text-dark text-decoration-none" %></li>
            <li class=""><%= day.lunch.dessert.title%></li>
            
          </ul>
          <li class="list-group-item text-light text-center bg-light">
            <b><%= link_to "Dîner", meal_path(day.dinner.id), class:"text-warning"%></b>
          </li>
          <ul class="list-group-item size-li-planning">    
            <li class="recipe"><i class="fas fa-plus-circle text-success"></i> <%= link_to day.dinner.starter.title, recipe_path(day.dinner.starter.id, ratio: current_user.needbymeal(day.dinner.category)/day.dinner.kcal),  remote: true, "data-target" => "#recipeModal", "data-toggle" =>"modal", class:"text-dark text-decoration-none" %></li>
            <li class=""><i class="fas fa-plus-circle text-success"></i> <%= link_to day.dinner.dish.title, recipe_path(day.dinner.dish.id, ratio: current_user.needbymeal(day.dinner.category)/day.dinner.kcal),  remote: true, "data-target" => "#recipeModal", "data-toggle" =>"modal", class:"text-dark text-decoration-none" %></li>
            <li class=""><%= day.dinner.dessert.title%></li>
          </ul>
        </ul>
      </div>
    <% end %>
  </div>
</div>

<div class="modal fade " id="recipeModal" tabindex="-1" role="dialog" aria-labelledby="recipeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="recipeBody">
      </div>
      <div class="modal-footer">
        <button tye="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>


<script>
var btn = document.getElementById("shopping-list");

btn.addEventListener("click", function(){
  var nav = document.getElementById("nav");
  nav.hidden = false

  }, false);

var close = document.getElementById("close");
close.addEventListener("click", function(){
  var nav = document.getElementById("nav");
  nav.hidden = true

  }, false);
</script>