config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
  devise_for :users
  
  scope 'users', module: 'users' do
    resources :users, only: [:show, :edit, :update]
    resources :recipes, only: [:show]
    resources :breakfast, only: [:show, :edit, :update]
    resources :meals, except: [:new, :index, :edit]
    resources :days, except: [:new, :index, :edit]
    resources :weeks, only: [:show, :create, :update]
    resources :shopping_emails, only: [:show]
    resources :charges, only: [:new, :create, :index]
  end

  scope 'admin', module: 'admin', as: 'admin' do
    resources :dashboard, only: [:index]
    resources :recipes
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nutriti</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/f56b9447bd.js" crossorigin="anonymous"></script>

  </head>

  <body>
<!-- Start of nav bar-->
    <nav class="navbar navbar-expand-lg navbar-white bg-success">
      <%= link_to image_tag("logo_nutriti.svg", height: 50), admin_dashboard_index_path, class:"navbar-brand ml-5" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to "Dashboard", admin_dashboard_index_path, class:"nav-link btn btn-warning"%>
          </li>
          <li class="nav-item">
            <%= link_to "Index des Recettes", admin_recipes_path, class:"nav-link btn btn-warning"%>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.first_name + " " + current_user.last_name%>
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Retour sur le site", root_path, class:"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Se déconnecter", destroy_user_session_path, class:"dropdown-item", method: :delete %>
            </div>
          </li>
        </ul>
      </div>
    </nav>    
<!-- End of nav bar-->

<!-- Flash -->
    <% flash.each do |key, value| %>
      <% if key == "error" %>
        <div class="alert alert-light alert-dismissible fade show" role="alert">
          <%= content_tag :span, value, class: "flash #{key}" %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% else %>
        <div class="alert alert-light alert-dismissible fade show" role="alert">
          <%= content_tag :span, value, class: "flash #{key}" %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
    <% end %>
<!-- End of Flash -->

<!-- Start of main-->
    <main role="main" class="flex-shrink-0">
      <div class="container">
            <%= yield %>
      </div>
    </main>
<!-- End of main-->

<!-- Start of footer-->
<!-- End of footer-->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nutriti</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://unpkg.com/@popperjs/core@2"></script>

    <script src="https://kit.fontawesome.com/e5ab504795.js" crossorigin="anonymous"></script>

  </head>

  <body>
    <!-- Start of navbar-->
    <nav class="navbar navbar-expand-lg navbar-white bg-white">
      <%= link_to image_tag("logo_nutriti.svg", height: 50), root_path, class:"navbar-brand ml-5" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item <%= 'active' if current_page?(root_path) %>">
          </li>        
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Menu
              </button>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                   <%= link_to "Voir profil", user_path(current_user.id), class: "dropdown-item" %>
                <% if current_user.is_admin %>
                  <%= link_to "Dashboard Admin", admin_dashboard_index_path, class:"dropdown-item" %>
                <% end %>
                <div class="dropdown-divider"></div>
                <%= link_to "Se déconnecter", destroy_user_session_path, class:"dropdown-item", method: :delete %>
              </div>
            </li>
            </li>
          <% else %>
            <li class="btn-group">
              <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                S'inscrire / Se connecter
              </button>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Inscription", new_user_registration_path, class:"dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Connexion", new_user_session_path, class:"dropdown-item" %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <!-- End of Navbar-->
    
    <%= yield %>

    <!-- Start of footer-->
    <% if current_page?(root_path) %>
    <footer class="page-footer mt-5">
        <div class="container-fluid bg-success py-1 text-center">
    <% else %>
    <footer class="page-footer fixed-bottom mt-5">
        <div class="container-fluid bg-success py-1 text-center">
    <% end %>
          <p class="text-white mt-2">
            <i class="far fa-copyright"></i> Fait avec <i class="fas fa-heart text-warning"></i> par l'équipage Nantais 
        </div>  
    </footer>
    <!-- End of footer-->
    
  
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nutriti</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/e5ab504795.js" crossorigin="anonymous"></script>
    

  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12" id="content">
          <nav class="navbar navbar-expand-lg navbar-white bg-white">
            <%= link_to image_tag("logo_nutriti.svg", height: 50), week_path(current_user.id), class:"navbar-brand ml-5" %>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <% unless current_page?(root_path) || current_page?(week_path(current_user.week.id)) %>          
              <h5 class="ml-2 my-3"><td class="nav-item <%= 'active' if current_page?(root_path) %> "><%= link_to "« Retour au planning", root_path, class:"text-warning text-decoration-none" %></td></h5>
              <% end %>
            </div>
            <button class="side-btn btn btn-outline-warning mr-2" id="nav-collapse" style="z-index: 9999;"><i class="fas fa-bars"></i></button>
          </nav>
        </div>

        <!-- Sidebar-->
        <div id="side-nav" class="container-right" style="display:none;">
          <div class="right-nav bg-white d-flex flex-column ">
            <h1 class="text-warning text-center mt-3 mb-2">Nutriti</h1>
            <hr>
            <tr class="nav flex-column align-items-start right-nav mt-4 ml-4">
              <% if current_user.is_admin %>
                <td class="nav-item align-self-center mr-4 mb-4">
                  <%= link_to "Dashboard Admin", admin_dashboard_index_path, class:"btn btn-warning" %>
                </td>   
              <% end %>
              <hr>
              <% unless current_page?(root_path) || current_page?(week_path(current_user.week.id)) %>          
                <h5 class="ml-2 my-3"><td class="nav-item <%= 'active' if current_page?(root_path) %> "><%= link_to "« Retour au planning", root_path, class:"text-warning text-decoration-none" %></td></h5>
              <% end %>
              <h5 class="ml-2 my-3"><td class="nav-item <%= 'active' if current_page?(user_path(current_user.id)) %> "><%= link_to "Voir profil", user_path(current_user.id), class: "text-warning text-decoration-none" %></td></h5>
        
              <h5 class="ml-2 my-3"><td class="nav-item"><%= link_to "Modifier son petit déjeuner", edit_breakfast_path(current_user.breakfast.id), "data-target" => "#breakfastModal", "data-toggle" =>"modal", remote: true,class:'text-warning text-decoration-none'%></td></h5>
              
              <% if current_user.is_premium %>
              <td class="nav-item"><h5 class="ml-2 my-3"><%= link_to "Générer un repas", meals_path, data:{method: 'post'}, class:'text-warning text-decoration-none'%></td></h5>
              
              <td class="nav-item"><h5 class="ml-2 my-3 mb-5"><%= link_to "Générer une journée", days_path, data:{method: 'post'}, class:'text-warning text-decoration-none'%></td></h5>
              
              <td class="nav-item"><p class="ml-2 my-3 mb-5"><%= link_to "Se désabonner du premium", user_path(current_user.id, user:{is_premium: false}), data:{method: 'put', confirm: "Êtes-vous sûr de vouloir vous désabonnez ? Vous perdrez toutes les fonctionnalités premium de Nutriti" }, class:'text-danger text-decoration-none'%></td></p>
        
              <% else %>
              <td class="nav-item"><h6 class="ml-2 my-3"><%= link_to "Générer un repas", charges_path, class:'text-warning text-decoration-none'%> <span class="badge badge-pill badge-light"><i class="far fa-star mr-2"></i> Premium</span></td></h6>
              
              <td class="nav-item"><h6 class="ml-2 my-3 mb-5"><%= link_to "Générer une journée", charges_path, class:'text-warning text-decoration-none'%> <span class="badge badge-pill badge-light"><i class="far fa-star mr-2"></i> Premium</span></td></h6>
              
              <h5 class="ml-2 my-3 mb-5 align-self-center mr-4"><td class="nav-item "><i class="far fa-star mr-2"></i> <%= link_to "Devenir Premium", charges_path, class:'text-warning text-decoration-none'%></td></h5>
              <% end %>
        
              <td class="nav-item <%= 'active' if current_page?(root_path) %> align-self-center mr-4 mt-5"><%= link_to "Se déconnecter", destroy_user_session_path, class:"btn btn-danger", method: :delete %></td>
            </tr>
          </div>
          <div class="side-blur" id="side-blur">
          </div>      
        </div>
        <!-- End of Sidebar-->
      </div>
    </div>

    <% if current_user.incomplete_profile? %>
      <div class="alert alert-warning" role="alert">
        Veuillez remplir vos informations pour profiter pleinement de nos fonctionnalités.  
      </div>
    <% end %>

    <!-- Flash -->
    <div class="container-fluid">
        <% flash.each do |key, value| %>
          <% if key == "error" %>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <%= content_tag :span, value, class: "flash #{key}" %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <% else %>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              <%= content_tag :span, value, class: "flash #{key}" %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <% end %>
        <% end %>
    </div>
    <div class="content">

      <%= yield %>

    </div>


  
    <!-- Footer -->
    <footer class="page-footer mt-5">
      <div class="bg-success py-1 text-center">
        <p class="text-white mt-2">
          <i class="far fa-copyright"></i> Fait avec <i class="fas fa-heart text-warning"></i> par l'équipage Nantais 
      </div>  
    </footer>    
    <!-- End of Footer -->


  <div class="modal fade " id="breakfastModal" tabindex="-1" role="dialog" aria-labelledby="breakfastModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="breakfastBody">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>

  <script>
let nav = document.getElementById("side-nav");
let blur = document.getElementById("side-blur");
let content = document.getElementById("content"); 
let button = document.getElementById("nav-collapse");
blur.addEventListener("click", function () {
  button.click();
});
button.addEventListener("click", function () {
    if (nav.style.display === "none") {
    nav.style.display = "block";
    button.animate([
      { transform: 'translateX(0px)' }, 
      { transform: 'translateX(-13vw)' }
    ], { 
      duration: 250,
    });
    nav.animate([
      { transform: 'translateX(+13vw)' }, 
      { transform: 'translateX(0px)' }
    ], { 
      duration: 250,
    });
    blur.animate([
      { transform: 'scale(2)' },
      { transform: 'scale(1)' },
    ], { 
      duration: 250,
    });
    button.style.transform = "translateX(-13vw)";
    button.classList.remove('btn-outline-warning');
    button.classList.add('btn-warning');
    blur.style.display = "block";

    } else {
        button.animate([
      { transform: 'translateX(-13vw)' }, 
      { transform: 'translateX(0px)' }
    ], { 
      duration: 250,
    });
    nav.animate([
      { transform: 'translateX(0px)' }, 
      { transform: 'translateX(+13vw)' }
    ], { 
      duration: 300,
    });
    

    button.style.transform = "translateX(0px)";
    button.classList.remove('btn-warning');
    button.classList.add('btn-outline-warning');
    blur.style.display = "none";
    setTimeout(hide, 300)
    function hide() {
      nav.style.display = "none";
    }
  }
})


window.setTimeout(function() {
    $(".alert-dismissible").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 1500);
</script>
  </body>
</html>